# Generated by Django 4.1.2 on 2022-11-28 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comorbidity', models.CharField(max_length=25)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('water', models.IntegerField()),
            ],
            options={
                'db_table': 'dailyValues',
            },
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('sodium', models.IntegerField()),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=5)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('water', models.IntegerField()),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('highBloodPressure', models.BooleanField()),
                ('stroke', models.BooleanField()),
                ('heartDisease', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('KidneyDiseaseStage', models.IntegerField()),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'units',
            },
        ),
    ]
