# Generated by Django 4.1.2 on 2022-11-28 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ManyToManyField(blank=True, to='health_app.meal'),
        ),
        migrations.AddField(
            model_name='meal',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.patient'),
        ),
    ]
