# Generated by Django 4.1.2 on 2022-11-28 23:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0002_ingredient_meal_meal_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highBloodPressure', models.BooleanField()),
                ('stroke', models.BooleanField()),
                ('heartDisease', models.BooleanField()),
                ('obesity', models.BooleanField()),
                ('smoker', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('KidneyDiseaseStage', models.IntegerField()),
            ],
            options={
                'db_table': 'Comorbidities',
            },
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('potassium', models.IntegerField()),
                ('phosphorous', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('water', models.IntegerField()),
            ],
            options={
                'db_table': 'Recipes',
            },
        ),
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='phosphorous',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='sodium',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='water',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='KidneyDiseaseStage',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='heartDisease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='highBloodPressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='stroke',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, max_length=5),
        ),
        migrations.AlterModelTable(
            name='dailyvalue',
            table='Daily Values',
        ),
        migrations.AlterModelTable(
            name='meal',
            table='Meals',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patients',
        ),
        migrations.AlterModelTable(
            name='units',
            table='Units',
        ),
        migrations.DeleteModel(
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.patient'),
        ),
        migrations.AddField(
            model_name='dailyvalue',
            name='comorbidity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='health_app.comorbidity'),
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.recipe'),
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbidity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='health_app.comorbidity'),
        ),
    ]
