# Generated by Django 4.1.2 on 2022-11-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0004_rename_units_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='patient',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='dailyvalue',
            name='Comorbidity',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='patient',
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='phosphorous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='sodium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dailyvalue',
            name='water',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='phosphorous',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='potassium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sodium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='water',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
