# Generated by Django 4.1.2 on 2022-11-29 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0005_rename_patient_user_rename_patient_meal_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=5),
        ),
    ]
