# Generated by Django 4.1.2 on 2022-11-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0007_rename_phosphorous_dailyvalue_phosphorus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='water',
        ),
    ]
