# Generated by Django 4.1.2 on 2022-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0008_remove_recipe_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comorbidity',
            name='heartDisease',
        ),
        migrations.RemoveField(
            model_name='comorbidity',
            name='obesity',
        ),
        migrations.RemoveField(
            model_name='comorbidity',
            name='smoker',
        ),
        migrations.RemoveField(
            model_name='comorbidity',
            name='stroke',
        ),
        migrations.AddField(
            model_name='recipe',
            name='water',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='phosphorous',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='sodium',
            field=models.FloatField(default=0),
        ),
    ]
