# Generated by Django 4.1.2 on 2022-11-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0009_remove_comorbidity_heartdisease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comorbidity',
            old_name='KidneyDiseaseStage',
            new_name='kidneyDiseaseStage',
        ),
    ]
