# Generated by Django 4.1.2 on 2022-11-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0010_rename_kidneydiseasestage_comorbidity_kidneydiseasestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
