# Generated by Django 4.1.2 on 2022-11-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0011_alter_user_email_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
