# Generated by Django 4.1.2 on 2022-11-30 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0012_rename_datetime_meal_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date_time',
        ),
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 11, 29), max_length=5),
        ),
    ]
