# Generated by Django 4.1.2 on 2022-11-30 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0013_remove_meal_date_time_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 29), max_length=5),
        ),
    ]
