# Generated by Django 4.1.2 on 2022-11-30 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0014_alter_meal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='phosphorous',
            new_name='phosphorus',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 30), max_length=5),
        ),
    ]
