# Generated by Django 4.1.2 on 2022-11-30 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0015_rename_phosphorous_recipe_phosphorus_alter_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, max_length=5),
        ),
    ]
