# Generated by Django 4.1.2 on 2022-11-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0020_rename_comorbidity_dvdeterminate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='dvdeterminate',
            name='sex',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
