# Generated by Django 4.1.2 on 2022-11-30 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_app', '0023_alter_dvdeterminate_sex'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dvdeterminate',
            table='Daily Value Determinates',
        ),
    ]
